name: yorum_platformu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # İkonlar
  cupertino_icons: ^1.0.8

  # Tarih ve Saat Formatlama
  intl: ^0.19.0
  
  # İnternet İstekleri (Resimli Bildirim İçin Şart)
  http: ^1.2.0

  # Firebase Temel Paketleri
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0

  # Bildirim Sistemi (FCM & Yerel Bildirim)
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1

  # Harita ve Konum İşlemleri
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

  # Medya, Görsel ve Paylaşım
  image_picker: ^1.1.2       # Fotoğraf seçme
  carousel_slider: ^5.0.0    # Çoklu resim kaydırma (Slider)
  share_plus: ^10.0.2        # Paylaş butonu için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # İKON OLUŞTURUCU
  flutter_launcher_icons: ^0.13.1
  
  # AÇILIŞ EKRANI OLUŞTURUCU (SPLASH)
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  
  # --- VARLIK TANITIMI ---
  assets:
    - assets/icon/

# --- UYGULAMA MENÜ İKONU AYARLARI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"         # Android bunu kullanır (Şeffaf olabilir)
  image_path_ios: "assets/icon/app_icon_ios.png" # iOS bunu kullanır (Arkası MUTLAKA DOLU olmalı)
  min_sdk_android: 21

# --- AÇILIŞ EKRANI (SPLASH) AYARLARI ---
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/app_icon.png"
  fullscreen: false 
  android_12:
    image: "assets/icon/app_icon.png"
    icon_background_color: "#FFFFFF"